---
- hosts: webservers
  become: yes
  tasks: 
  - name: install java 8 on ubuntu
    apt:
      name: "{{myjavaonubuntu}}"
      state: present
    when: ansible_os_family =="Debian"
  
  - name: install java 8 on redhat
    yum:
      name: "{{myjavaonredhat}}"
      state: present
    when: ansible_os_family =="Redhat"