---
- hosts: 172.31.46.104 
  become: yes
  tasks:
  - name: execute hostname 
    command: hostname -f
    register: myresult

  - name: display my first task result
    debug:
      msg: "{{myresult}}"